name: orion_flutter
description: Orion Flutter SDK (binary-only)
homepage: https://github.com/epsilondelta-speed/ep_orion_flutter
repository: https://github.com/epsilondelta-speed/ep_orion_flutter
version: 1.2.34

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  dio: ^5.2.1
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: co.epsilondelta.orion_flutter
        pluginClass: OrionFlutterPlugin
      ios:
        pluginClass: OrionFlutterPlugin
