name: orion_flutter
homepage: https://github.com/epsilondelta-speed/ep_orion_flutter
repository: https://github.com/epsilondelta-speed/ep_orion_flutter
description: Orion Flutter SDK (binary-only)
version: 1.2.22
flutter:
  plugin:
    platforms:
      android:
        package: co.epsilondelta.orion_flutter
        pluginClass: OrionFlutterPlugin
      ios:
        pluginClass: OrionFlutterPlugin

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter


